# Generated by Django 4.0.5 on 2022-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating1', models.IntegerField(null=True)),
                ('rating2', models.IntegerField(null=True)),
                ('rating3', models.IntegerField(null=True)),
                ('rating4', models.IntegerField(null=True)),
                ('feedback', models.TextField(null=True)),
            ],
        ),
    ]
